// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bertrand} from '../models';

export function FirstMethod(arg1:number,arg2:number):Promise<bertrand.FirstMethodResult>;

export function GenerateAllCatalanPathPoints(arg1:number):Promise<Array<any>>;

export function Greet(arg1:string):Promise<string>;

export function SecondMethod(arg1:number,arg2:number):Promise<bertrand.SecondMethodResult>;

export function ThirdMethod(arg1:number,arg2:number):Promise<bertrand.ThirdMethodResult>;
