// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FirstMethod(arg1, arg2) {
  return window['go']['main']['App']['FirstMethod'](arg1, arg2);
}

export function GenerateAllCatalanPathPoints(arg1) {
  return window['go']['main']['App']['GenerateAllCatalanPathPoints'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PrisonersProblem(arg1) {
  return window['go']['main']['App']['PrisonersProblem'](arg1);
}

export function SecondMethod(arg1, arg2) {
  return window['go']['main']['App']['SecondMethod'](arg1, arg2);
}

export function ThirdMethod(arg1, arg2) {
  return window['go']['main']['App']['ThirdMethod'](arg1, arg2);
}
