name: Wails Cross-Platform Build & Release

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發
  pull_request:
    branches:
      - main  # 當 PR 合併到 main 分支時觸發

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [
          { name: linux-amd64, os: ubuntu-latest, build-platform: linux/amd64 },
          { name: wailsApp-windows-amd64, os: windows-latest, build-platform: windows/amd64 },
          { name: wailsApp-windows-arm64, os: windows-latest, build-platform: windows/arm64 },
          { name: wailsApp-macos-arm64, os: macos-latest, build-platform: darwin/arm64 },
          { name: wailsApp-macos-amd64, os: macos-latest, build-platform: darwin/amd64 }
        ]
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.platform.name }}
          build-platform: ${{ matrix.platform.build-platform }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.name }}
          path: ./build

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./release

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          name: ${{ matrix.platform.name }}
          path: ./release/${{ matrix.platform.name }}
          label: ${{ matrix.platform.name }}
